$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.12.0/schemas/v4/install.json
artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.14.4
    requires:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.10.5
  "@daiyam/artifact-vsx-ts":
    version: 0.11.14
    update:
      src/**:
        if_exists: skip
        if_missing: skip
  "@daiyam/artifact-vsx-zokugun":
    version: 0.4.2
  "@daiyam/artifact-vsx-bundle-ncc":
    version: 0.4.2
  "@daiyam/artifact-vsx-test-mocha":
    version: 0.1.2
    features:
      - test
  "@daiyam/artifact-gh-issuehub":
    version: 0.6.5
variables:
  DISCUSSION_ID: 154
  ISSUE_ID: 153
