artifacts:
  - name: "@daiyam/artifact-base"
    version: 0.5.0
  - name: "@daiyam/artifact-lang-ts"
    version: 0.4.0
  - name: "@daiyam/artifact-vsx-ts"
    version: 0.5.1
  - name: "@daiyam/artifact-vsx-zokugun"
    version: 0.2.0
  - name: "@daiyam/artifact-vsx-bundle-ncc"
    version: 0.3.0
