artifacts:
  - name: "@daiyam/artifact-lang-js"
    version: 0.6.1
  - name: "@daiyam/artifact-lang-ts"
    version: 0.5.5
  - name: "@daiyam/artifact-vsx-ts"
    version: 0.7.2
  - name: "@daiyam/artifact-vsx-zokugun"
    version: 0.3.1
  - name: "@daiyam/artifact-vsx-bundle-ncc"
    version: 0.4.0
