labels: ["S-needs-triage"]
body:
  - type: markdown
    attributes:
      value: |-
        > [!IMPORTANT]
        > Please read through [the Discussion rules](https://github.com/zokugun/vscode-explicit-folding/discussions/154) and check for both existing [Discussions](https://github.com/zokugun/vscode-explicit-folding/discussions?discussions_q=) and [Issues](https://github.com/zokugun/vscode-explicit-folding/issues?q=sort%3Areactions-desc) prior to opening a new Discussion.
  - type: markdown
    attributes:
      value: "# Issue Details"
  - type: textarea
    attributes:
      label: Issue Description
      description: |-
        Provide a detailed description of the issue. Include relevant informations.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |-
        Describe how you expect this project to behave in this situation. Include any relevant documentation links.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: |-
        Describe how this project actually behaves in this situation. If it is not immediately obvious how the actual behavior differs from the expected behavior described above, please be sure to mention the deviation specifically.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code Example
      description: Provide a code example.
      placeholder: |
        ```
        class Foobar {
        }
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Settings
      description: Provide the settings used. This will be automatically formatted into JSONC, so no need for backticks.
      render: jsonc
      placeholder: |
        "folding": {
          "*": {
            "begin": "{{{",
            "end": "}}}",
          }
        }
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        - VSCode: v1.110.0
        - Explicit Folding: v0.24.3
        - Language: COBOL
        - Language Provider: IBM Z Open Editor <!-- if applicable, the extension which adds the language support -->
      value: |
        - VSCode:
        - Explicit Folding:
        - Language:
        - Language Provider:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        # User Acknowledgements
        > [!TIP]
        > Use these links to review the existing [Discussions](https://github.com/zokugun/vscode-explicit-folding/discussions?discussions_q=) and [Issues](https://github.com/zokugun/vscode-explicit-folding/issues?q=sort%3Areactions-desc).
  - type: checkboxes
    attributes:
      label: "I acknowledge that:"
      options:
        - label: I have reviewed the FAQ and confirm that my issue is NOT among them.
          required: true
        - label: I have searched the repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
          required: true
        - label: I have checked the "Preview" tab on all text fields to ensure that everything looks right, and have wrapped all configuration and code in code blocks with a group of three backticks (` ``` `) on separate lines.
          required: true
